<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllNotDeleted()
    {
        return $this->findBy(['deletedAt' => null]);
    }

    /**
     * @param Project $project
     * @param int $limit
     * @return array
     */
    public function findBySimilarType(Project $project, $limit = 4)
    {
        return $this->createQueryBuilder("q")
            ->where("q.type = :type")
            ->andWhere("q.id != :id")
            ->andWhere("q.deletedAt IS NULL")
            ->setParameters(['type' => $project->getType(), "id" => $project->getId()])
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $string
     * @return array
     */
    public function findByString($string)
    {
        $string = "%$string%";
        return $this->createQueryBuilder("q")
            ->leftJoin("q.type", "type")
            ->where("type.name LIKE  $string")
            ->orWhere("type.file LIKE $string ")
            ->orWhere("type.slug LIKE  $string")
            ->orWhere("project.title LIKE  $string")
            ->orWhere("project.description LIKE  $string")
            ->orWhere("project.fullDescription LIKE  $string")
            ->orWhere("project.slug LIKE  $string")
            ->andWhere("q.deletedAt IS NULL")
            ->getQuery()
            ->getResult();
    }


}
