# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.doctrine_projects_listener:
      class: AppBundle\EventListener\UploadListener
      arguments: ["%project_directory%","%type_directory%"]
      tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: postLoad }
  app.custom_authenticator:
      class: AdminBundle\Security\CustomAuthenticator
      arguments: ["@service_container"]

