# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.custom_authenticator:
      class: AdminBundle\Security\CustomAuthenticator
      arguments: ["@service_container"]

    #Event Listener
  app.doctrine_projects_listener:
      class: AppBundle\EventListener\UploadListener
      arguments: ["%project_directory%","%type_directory%"]
      tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: postLoad }

  admin.menu_listener:
        class: AdminBundle\EventListener\ListListener
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }

  app.last_login_subscriber:
        class: AdminBundle\EventListener\LastLoginSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }