<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param string $username
     * @return User|null
     */
    public function findByUsernameOrEmail($username)
    {
        return $this->createQueryBuilder('u')
            ->andWhere('UPPER(u.username) = :username OR UPPER(u.email) = :username')
            ->setParameter('username', strtoupper($username))
            ->getQuery()
            ->getOneOrNullResult();
    }

}
