<?php
/**
 * Created by PhpStorm.
 * User: Maps_red
 * Date: 29/08/2016
 * Time: 22:45
 */

return $projects = [
    [
        'id' => '1',
        'title' => 'Traduction - En 60S Yoga !',
        'description' => 'Traduction directement dans After Effects d\'un leader pour la sÃ©rie Kids&Parenting',
        'image' => 'ThumbsPortfolioZoominTV_60S translation.jpg',
        'type' => '1',
        'slug' => 'traduction-en-60s-yoga',
        'updated_at' => '2016-08-18 07:32:15',
        'created_at' => '2016-08-12 05:00:03',
        'deleted_at' => null,
    ],
    [
        'id' => '2',
        'title' => 'Thumbnail - Bubble Man',
        'description' => 'RÃ©alisation d\'une thumbnail sous Photoshop',
        'image' => 'ThumbsPortfolioZoominTV_BubbleMan.jpg',
        'type' => '5',
        'slug' => 'thumbnail-bubble-man',
        'updated_at' => '2016-08-12 05:00:47',
        'created_at' => '2016-08-12 05:00:47',
        'deleted_at' => null,
    ],
    [
        'id' => '3',
        'title' => 'Thumbnail - Cam Girl',
        'description' => 'RÃ©alisation d\'une thumbnail sous Illustrator',
        'image' => 'ThumbsPortfolioZoominTV_CamGirl.jpg',
        'type' => '2',
        'slug' => 'thumbnail-cam-girl',
        'updated_at' => '2016-08-12 05:02:18',
        'created_at' => '2016-08-12 05:02:18',
        'deleted_at' => null,
    ],
    [
        'id' => '4',
        'title' => 'Animation - Cupid\'s Arrow',
        'description' => 'Petite animation faite sous After Effects pour illustrer une news.',
        'image' => 'ThumbsPortfolioZoominTV_CupidArrow.jpg',
        'type' => '1',
        'slug' => 'animation-cupid-s-arrow',
        'updated_at' => '2016-08-12 05:03:23',
        'created_at' => '2016-08-12 05:03:23',
        'deleted_at' => null,
    ],
    [
        'id' => '5',
        'title' => 'Animation - Cursed Pictures',
        'description' => 'Petite animation faite sous After Effects pour illustrer une news.',
        'image' => 'ThumbsPortfolioZoominTV_CursedPictures.jpg',
        'type' => '1',
        'slug' => 'animation-cursed-pictures',
        'updated_at' => '2016-08-12 05:05:12',
        'created_at' => '2016-08-12 05:05:12',
        'deleted_at' => null,
    ],
    [
        'id' => '6',
        'title' => 'Infographic - Dinosaurs',
        'description' => 'Infographie dans un essai d\'un nouveau style',
        'image' => 'ThumbsPortfolioZoominTV_Dinosaurs.jpg',
        'type' => '1',
        'slug' => 'infographic-dinosaurs',
        'updated_at' => '2016-08-12 05:05:57',
        'created_at' => '2016-08-12 05:05:57',
        'deleted_at' => null,
    ],
    [
        'id' => '7',
        'title' => 'Animation - ESL Benelux',
        'description' => 'Petite animation faite sous After Effects pour un partenaire.',
        'image' => 'ThumbsPortfolioZoominTV_ESLBenelux.jpg',
        'type' => '1',
        'slug' => 'animation-esl-benelux',
        'updated_at' => '2016-08-12 05:06:25',
        'created_at' => '2016-08-12 05:06:25',
        'deleted_at' => null,
    ],
    [
        'id' => '8',
        'title' => 'Footballers Cutouts',
        'description' => 'DÃ©tourage de photos faÃ§on dÃ©coupage',
        'image' => 'ThumbsPortfolioZoominTV_FootballersCutouts.jpg',
        'type' => '3',
        'slug' => 'footballers-cutouts',
        'updated_at' => '2016-08-29 10:04:35',
        'created_at' => '2016-08-12 05:07:12',
        'deleted_at' => null,
    ],
    [
        'id' => '9',
        'title' => 'Headlines Animation',
        'description' => 'Animation en alpha représentant des titres de journaux dans le style New-York Times.',
        'image' => 'ThumbsPortfolioZoominTV_Headlines.jpg',
        'type' => '1',
        'slug' => 'headlines-animation',
        'updated_at' => '2016-08-16 02:55:53',
        'created_at' => '2016-08-16 02:55:53',
        'deleted_at' => null,
    ],
    [
        'id' => '10',
        'title' => 'Map - Outline Style',
        'description' => 'Map en alpha dans le style outline pour certaines vidéos.',
        'image' => 'ThumbsPortfolioZoominTV_ItaliaMap.jpg',
        'type' => '1',
        'slug' => 'outline-map',
        'updated_at' => '2016-08-16 02:56:48',
        'created_at' => '2016-08-16 02:56:48',
        'deleted_at' => null,
    ],
    [
        'id' => '11',
        'title' => 'Infographics - Knights',
        'description' => 'Infographie sur les armures des chevaliers.',
        'image' => 'ThumbsPortfolioZoominTV_Knights.jpg',
        'type' => '1',
        'slug' => 'infographics-knights',
        'updated_at' => '2016-08-16 02:58:51',
        'created_at' => '2016-08-16 02:58:51',
        'deleted_at' => null,
    ],
    [
        'id' => '12',
        'title' => 'Thumbnail - Live Event Party',
        'description' => 'Thumbnail pour un Ã©vÃ©nement live.',
        'image' => 'ThumbsPortfolioZoominTV_LiveEventFesti.jpg',
        'type' => '5',
        'slug' => 'thumbnail-live-event-party',
        'updated_at' => '2016-08-16 02:59:32',
        'created_at' => '2016-08-16 02:59:32',
        'deleted_at' => null,
    ],
    [
        'id' => '13',
        'title' => 'Thumbnail - Movie monday',
        'description' => 'Thumbnail rÃ©alisÃ©e depuis un template avec l\'overlay correspondant.',
        'image' => 'ThumbsPortfolioZoominTV_MovieMonday.jpg',
        'type' => '5',
        'slug' => 'thumbnail-movie-monday',
        'updated_at' => '2016-08-16 03:05:43',
        'created_at' => '2016-08-16 03:05:43',
        'deleted_at' => null,
    ],
    [
        'id' => '14',
        'title' => 'Infographic - Nails Biting',
        'description' => 'Infographie Ã  propos des personnes qui rongent leurs ongles.',
        'image' => 'ThumbsPortfolioZoominTV_NailBiting.jpg',
        'type' => '1',
        'slug' => 'infographic-nails-biting',
        'updated_at' => '2016-08-16 03:11:04',
        'created_at' => '2016-08-16 03:11:04',
        'deleted_at' => null,
    ],
    [
        'id' => '15',
        'title' => 'Amazon Referrals Leaflet',
        'description' => 'Traduction d\'un flyer dans InDesign pour le desk portuguais.',
        'image' => 'ThumbsPortfolioZoominTV_AmazonLeaflet.jpg',
        'type' => '4',
        'slug' => 'amazon-referrals-leaflet',
        'updated_at' => '2016-08-16 03:13:05',
        'created_at' => '2016-08-16 03:13:05',
        'deleted_at' => null,
    ],
    [
        'id' => '16',
        'title' => 'Infographic - Perfume',
        'description' => 'Infographie Ã  propos des diffÃ©rentes sortes de parfums et de leurs prix.',
        'image' => 'ThumbsPortfolioZoominTV_Perfume .jpg',
        'type' => '1',
        'slug' => 'infographic-perfume',
        'updated_at' => '2016-08-16 03:14:03',
        'created_at' => '2016-08-16 03:14:03',
        'deleted_at' => null,
    ],
    [
        'id' => '17',
        'title' => 'Graphic - PaddlePop Typo',
        'description' => 'Ecriture de quelques mots-clÃ©s dans un style et une typo particuliÃ¨re dans Photoshop et export en png pour les glaces PaddlePop.',
        'image' => 'ThumbsPortfolioZoominTV_Paddlepop-words.jpg',
        'type' => '3',
        'slug' => 'paddlepop-typo',
        'updated_at' => '2016-08-16 03:15:09',
        'created_at' => '2016-08-16 03:15:09',
        'deleted_at' => null,
    ],
    [
        'id' => '18',
        'title' => 'Thumbnail - PokÃ©mon Go Live',
        'description' => 'RÃ©alisation d\'une thumbnail pour un Ã©vÃ©nement live autour du jeu PokÃ©mon Go.',
        'image' => 'ThumbsPortfolioZoominTV_PokemonGOMadrid.jpg',
        'type' => '5',
        'slug' => 'thumbnail-pokemon-go-live-event',
        'updated_at' => '2016-08-16 03:16:43',
        'created_at' => '2016-08-16 03:16:43',
        'deleted_at' => null,
    ],
    [
        'id' => '19',
        'title' => 'Animation - Rio Sustainability',
        'description' => 'Petite animation illustrant les trois pilliers de Rio pour les JO.',
        'image' => 'ThumbsPortfolioZoominTV_RioSustainability.jpg',
        'type' => '1',
        'slug' => 'animation-rio-sustainability',
        'updated_at' => '2016-08-16 03:18:45',
        'created_at' => '2016-08-16 03:18:45',
        'deleted_at' => null,
    ],
    [
        'id' => '20',
        'title' => 'Animation - Ronaldo VS Gareth',
        'description' => 'Animation faites sous After Effects pour montrer la rivalitÃ© des deux joueurs.',
        'image' => 'ThumbsPortfolioZoominTV_RonaldoVSGarethBale.jpg',
        'type' => '1',
        'slug' => 'animation-ronaldo-vs-gareth',
        'updated_at' => '2016-08-16 03:41:40',
        'created_at' => '2016-08-16 03:41:40',
        'deleted_at' => null,
    ],
    [
        'id' => '21',
        'title' => 'Animation - Ronaldo VS Messi',
        'description' => 'Animation de type course en sac pour montrer les diffÃ©rentes Ã©tapes de carriÃ¨re des deux joueurs.',
        'image' => 'ThumbsPortfolioZoominTV_RonaldoVSMessi.jpg',
        'type' => '1',
        'slug' => 'animation-ronaldo-vs-messi',
        'updated_at' => '2016-08-16 03:44:35',
        'created_at' => '2016-08-16 03:44:35',
        'deleted_at' => null,
    ],
    [
        'id' => '22',
        'title' => 'Traduction - Shark Week',
        'description' => 'Traduction des diffÃ©rentes thumbnails d\'Ã©pisodes en plusieurs langues.',
        'image' => 'ThumbsPortfolioZoominTV_SharkWeekEN.jpg',
        'type' => '5',
        'slug' => 'traduction-shark-week-thumbnails',
        'updated_at' => '2016-08-16 03:47:38',
        'created_at' => '2016-08-16 03:47:38',
        'deleted_at' => null,
    ],
    [
        'id' => '23',
        'title' => 'Infographic - Slugs and Salt',
        'description' => 'Infographie classÃ©e dans biologie, parlant de la rÃ©action naturelle des limaces au sel.',
        'image' => 'ThumbsPortfolioZoominTV_Slugs&Salt.jpg',
        'type' => '1',
        'slug' => 'infographic-slugs-and-salt',
        'updated_at' => '2016-08-16 03:48:55',
        'created_at' => '2016-08-16 03:48:55',
        'deleted_at' => null,
    ],
    [
        'id' => '24',
        'title' => 'Graphic - Snapchat Layouts',
        'description' => 'DÃ©tourage des icÃ´nes Snapchat pour utilisation alpha et crÃ©ation d\'un placeholder.',
        'image' => 'ThumbsPortfolioZoominTV_SnapchatLayouts.jpg',
        'type' => '3',
        'slug' => 'graphic-snapchat-layouts',
        'updated_at' => '2016-08-16 03:54:37',
        'created_at' => '2016-08-16 03:54:37',
        'deleted_at' => null,
    ],
    [
        'id' => '25',
        'title' => 'Infographic - Super Heroes',
        'description' => 'Infographie comparant Batman et Superman d\'un point de vue scientifique.',
        'image' => 'ThumbsPortfolioZoominTV_SuperHeroes.jpg',
        'type' => '1',
        'slug' => 'infographic-super-heroes',
        'updated_at' => '2016-08-16 03:55:27',
        'created_at' => '2016-08-16 03:55:27',
        'deleted_at' => null,
    ],
    [
        'id' => '26',
        'title' => 'Template Mailchimp',
        'description' => 'CrÃ©ation d\'un template directement dans MailChimp Ã  l\'aide de HTML et des modules front-end personnalisables.',
        'image' => 'ThumbsPortfolioZoominTV_TemplateMailchimp.jpg',
        'type' => '3',
        'slug' => 'template-mailchimp',
        'updated_at' => '2016-08-16 03:58:07',
        'created_at' => '2016-08-16 03:58:07',
        'deleted_at' => null,
    ],
    [
        'id' => '27',
        'title' => 'Thumbnail - Tetaton Bogota',
        'description' => 'Thumbnail pour un Ã©vÃ©nement live.',
        'image' => 'ThumbsPortfolioZoominTV_TetatonBogota.jpg',
        'type' => '5',
        'slug' => 'thumbnail-tetaton-bogota',
        'updated_at' => '2016-08-16 03:58:36',
        'created_at' => '2016-08-16 03:58:36',
        'deleted_at' => null,
    ],
    [
        'id' => '28',
        'title' => 'Animation - Zayn & Aliens',
        'description' => 'Animation de Zayn Malik se faisant enlever par les aliens.',
        'image' => 'ThumbsPortfolioZoominTV_ZaynMalik&theAliens.jpg',
        'type' => '1',
        'slug' => 'animation-zayn-aliens',
        'updated_at' => '2016-08-16 03:59:26',
        'created_at' => '2016-08-16 03:59:26',
        'deleted_at' => null,
    ],
    [
        'id' => '29',
        'title' => 'Animation - Mine',
        'description' => 'Animation schÃ©matique illustrant une news, montrant le danger de l\'accumulation de CO2 dans une mine artificielle.',
        'image' => 'ThumbsPortfolioZoominTV_MineAnimation.jpg',
        'type' => '1',
        'slug' => 'animation-mine',
        'updated_at' => '2016-08-16 04:02:14',
        'created_at' => '2016-08-16 04:02:14',
        'deleted_at' => null,
    ],
    [
        'id' => '30',
        'title' => 'Infographic - Garbage',
        'description' => 'Infographie Ã  propos de la gestion des dÃ©chets en SuÃ¨de.',
        'image' => 'ThumbsPortfolioZoominTV_Garbage.jpg',
        'type' => '1',
        'slug' => 'infographic-garbage',
        'updated_at' => '2016-08-16 05:04:10',
        'created_at' => '2016-08-16 05:04:10',
        'deleted_at' => null,
    ],
    [
        'id' => '31',
        'title' => 'Map - News Style',
        'description' => 'Map pour les news avec la zone recherchÃ©e en rouge.',
        'image' => 'ThumbsPortfolioZoominTV_NewsMap.jpg',
        'type' => '1',
        'slug' => 'map-news-style',
        'updated_at' => '2016-08-16 05:14:03',
        'created_at' => '2016-08-16 05:14:03',
        'deleted_at' => null,
    ],
];